# Generated by Django 2.2.5 on 2019-09-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Source main page URL')),
                ('parser', models.CharField(choices=[('default', 'Default'), ('default', 'UA Pravda')], default='default', max_length=20, verbose_name='Parser')),
                ('last_parsed', models.DateTimeField(auto_now_add=True, verbose_name='Last parsed')),
            ],
        ),
    ]
