# Generated by Django 2.2.5 on 2019-09-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={'verbose_name': 'Джерело', 'verbose_name_plural': 'Джерела'},
        ),
        migrations.AlterField(
            model_name='newssource',
            name='parser',
            field=models.CharField(choices=[('default', 'Default'), ('uapravda', 'UA Pravda')], default='default', max_length=20, verbose_name='Parser'),
        ),
    ]
