# Generated by Django 2.2.5 on 2019-09-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0002_auto_20190924_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newssource',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
    ]
