# Generated by Django 2.2.5 on 2019-09-24 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0003_auto_20190924_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newssources.NewsSource')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
            },
        ),
    ]
