# Generated by Django 2.2.5 on 2019-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0004_newsmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmessage',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Title'),
        ),
    ]
