# Generated by Django 2.2.5 on 2019-10-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0005_auto_20191001_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmessage',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
