# Generated by Django 2.2.5 on 2019-10-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newssources', '0006_newsmessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('completed', 'Completed')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
