# Generated by Django 2.2.5 on 2019-10-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Text')),
                ('link', models.URLField(max_length=250, verbose_name='Link')),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('status', models.CharField(choices=[('new', 'New'), ('completed', 'Completed')], default='new', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'News item',
                'verbose_name_plural': 'News items',
            },
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(verbose_name='Source main page URL')),
                ('parser', models.CharField(choices=[('default', 'Default'), ('uapravda', 'UA Pravda')], default='default', max_length=20, verbose_name='Parser')),
                ('last_parsed', models.DateTimeField(auto_now_add=True, verbose_name='Last parsed')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='NewsTonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tonality', models.CharField(choices=[(0, 'Neutral'), (1, 'Positive'), (-1, 'Negative')], default=0, max_length=10, verbose_name='Tonality')),
                ('tonality_index', models.IntegerField(default=0, verbose_name='Tonality index')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NewsMessage')),
            ],
            options={
                'verbose_name': 'Tonality',
                'verbose_name_plural': 'Tonalities',
            },
        ),
        migrations.AddField(
            model_name='newsmessage',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.NewsSource'),
        ),
    ]
