# Generated by Django 2.2.5 on 2019-10-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_newstonaldaily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstonaldaily',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
