# Generated by Django 2.2.5 on 2019-10-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20191030_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstonal',
            name='tonality_index',
            field=models.FloatField(default=0, verbose_name='Tonality index'),
        ),
    ]
