# Generated by Django 2.2.5 on 2019-10-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20191030_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstonal',
            name='tonality',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Positive'), (-1, 'Negative')], default=0, verbose_name='Tonality'),
        ),
        migrations.AlterField(
            model_name='newstonaldaily',
            name='tonality',
            field=models.IntegerField(choices=[(0, 'Neutral'), (1, 'Positive'), (-1, 'Negative')], default=0, verbose_name='Tonality'),
        ),
    ]
