# Generated by Django 2.2.5 on 2019-10-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20191030_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='parser',
            field=models.CharField(choices=[('default', 'Default'), ('uapravda', 'UA Pravda'), ('obozrevatel', 'Obozrevatel')], default='default', max_length=20, verbose_name='Parser'),
        ),
    ]
