# Generated by Django 2.2.5 on 2019-11-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_auto_20191030_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='parser',
            field=models.CharField(choices=[('default', 'Default'), ('uapravda', 'UA Pravda'), ('obozrevatel', 'Obozrevatel'), ('segodnya', 'Segodnya'), ('ua24', '24 channel'), ('rbc', 'RBC'), ('znaj', 'Znaj')], default='default', max_length=20, verbose_name='Parser'),
        ),
    ]
