# Generated by Django 2.2.5 on 2019-11-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20191106_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssource',
            name='desctiption',
            field=models.TextField(default='', verbose_name='Desctiption'),
        ),
        migrations.AddField(
            model_name='newssource',
            name='logo',
            field=models.ImageField(default='', upload_to='uploads/', verbose_name='Logo'),
            preserve_default=False,
        ),
    ]
