# Generated by Django 2.2.5 on 2019-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20191107_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newssource',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Logo'),
        ),
    ]
