# Generated by Django 2.2.5 on 2019-11-08 12:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Text'),
        ),
    ]
