# Generated by Django 2.2.5 on 2020-01-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
