# Generated by Django 3.0 on 2020-01-15 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmessage',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Date'),
        ),
    ]
