# Generated by Django 3.0 on 2020-01-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20200115_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmessage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
